### PR TITLE
Re-write supporter page

### PR DESCRIPTION
**Pull request by Waterdrips**
This updates the support page to new style to match the homepage

# After

Screenshot from 2020-02-04 16-57-28
Screenshot from 2020-02-04 16-57-36

# Before

Screenshot from 2020-02-04 16-08-07

Screenshot from 2020-02-04 16-08-20

### CODE REVIEW

**Comment by alexellis** [comment]
I do like the sub-heading if you can bring that back to break up the whitespace?

**Comment by alexellis** [comment]
Thank you for doing this, it looks much much better.

**Comment by Waterdrips** [comment]
I have added and pushed. Screenshot:
image

**Comment by alexellis** [comment]
Thank you. Merged

**Pull request merged**
