### PR TITLE
Fix Youtube player

### PR DESCRIPTION
**Pull request by Waterdrips**
The YouTube player API appears to have changed, iv made a fix and tested locally.

Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for doing this so quickly and to @marcosnils for reporting

**Comment by alexellis** [comment]
There used to be a play icon too, did this disappear when we removed the "video demo" navigation link from the bar?

**Comment by alexellis** [comment]
Still appears to be broken at my end @Waterdrips - fairly sure it's redeployed because I refreshed the stats and they are now 21.6k vs 21.4k when your PR was merged.

**Comment by Waterdrips** [comment]
I think this is a cache issue. If you clear the cache or do a hard refresh (ctrl+shift+r on linux)

**Pull request merged**
