### PR TITLE
Code examples homepage

### LINKED ISSUE #106: Code examples on Homepage
```
faas-cli template store pull golang-http
faas-cli new --lang golang-http golang-http-fn

handler.go

package function

import (
	"fmt"
	"net/http"

	"github.com/openfaas-incubator/go-function-sdk"
)

// Handle a function invocation
func Handle(req handler.Request) (handler.Response, error) {
	var err error

	message := fmt.Sprintf("Hello world, input was: %s", string(req.Body))

	return handler.Response{
		Body:       []byte(message),
		StatusCode: http.StatusOK,
	}, err
}

```

```
faas-cli template store pull node10-express
faas-cli new --lang node10-express express-fn

// handler.js
"use strict"

module.exports = (event, context) => {
    let err;
    const result =             {
        status: "You said: " + JSON.stringify(event.body)
    };

    context
        .status(200)
        .succeed(result);
}
```

```
faas-cli template store pull node10-express
faas-cli new --lang node10-express javascript-fn

// handler.js
"use strict"

module.exports = (event, context) => {
    let err;
    const result =             {
        status: "You said: " + JSON.stringify(event.body)
    };

    context
        .status(200)
        .succeed(result);
}
```

```
faas-cli new --lang python3 --lang python3-fn

handler.py

def handle(req):
    """handle a request to the function
    Args:
        req (str): request body
    """

    return req
```

```
faas-cli new --lang java8 java-fn

Handler.java

package com.openfaas.function;

import com.openfaas.model.IHandler;
import com.openfaas.model.IResponse;
import com.openfaas.model.IRequest;
import com.openfaas.model.Response;

public class Handler implements com.openfaas.model.IHandler {

    public IResponse Handle(IRequest req) {
        Response res = new Response();
	    res.setBody("Hello, world!");

	    return res;
    }
}
```

### PR DESCRIPTION
**Pull request by Waterdrips**
# Description
This adds a selection of code examples to the homepage:
Fixes #106 
Screenshots here:

Screenshot from 2020-02-05 17-24-28

Screenshot from 2020-02-05 17-25-01
Screenshot from 2020-02-05 17-24-37
Screenshot from 2020-02-05 17-24-50

### CODE REVIEW

**Comment by alexellis** [comment]
Can I merge it?

**Comment by Waterdrips** [comment]
> Can I merge it?

By all means

**Comment by jonatasbaldin** [comment]
I think we could use at most 5 languages, the most used ones, other way it will have a pain to maintain.

I'd also think about including BASH, since it's quite a nice use case inside OpenFaaS, where other FaaS providers usually don't support it.

**Comment by alexellis** [comment]
For bash, we have the streaming template. Perhaps we can get that into the main openfaas/templates repo now?

https://github.com/alexellis/openfaas-streaming-templates

**Comment by alexellis** [comment]
I would like to see golang-middleware (as a microservice example) and a Dockerfile example.

**Pull request merged**
