### PR TITLE
Address vulnerability alerts for jekyll and rubyzip

### PR DESCRIPTION
**Pull request by johnmccabe**
This PR bumps the `Gemfile.lock` to pull in newer versions of `jekyll` and `rubyzip`, this should address the alerts raised below.

image

### CODE REVIEW

**Comment by johnmccabe** [comment]
ping @alexellis

**Comment by alexellis** [comment]
Thank you John. For future reference how did you bump the versions?

Alex

**Comment by alexellis** [comment]
Did `docker-compose up` render a working site on your local computer too?

**Comment by johnmccabe** [comment]
Yes, did it not do so for you??

**Comment by johnmccabe** [comment]
Delete the old lock, `brew bundle` to a vendor dir then test

**Comment by alexellis** [comment]
Great.. I'll merge it now. 

Please could you add this instruction to the README for future reference? 

https://github.com/openfaas/openfaas.github.io/pull/41#issuecomment-442766433

**Pull request merged**
