### PR TITLE
Add call to action areas

### PR DESCRIPTION
**Pull request by burtonr**
Signed-off-by: Burton Rheutan <rheutan7@gmail.com>

Adding the 2 sections from the new design for call to actions.
Using the CSS grid feature to ensure the alignment remains through various screen sizes.

Still some work to do for mobile however. I assume we would want them stacked on small screen devices to ensure better readability. I'll continue toward that goal next. In the meantime, I appreciate any feedback on the design so far.

### CODE REVIEW

**Comment by burtonr** [comment]
Here's a screen shot of what it looks like on the initial commit.

The assets from the design are not yet available, so I downloaded one and duplicated it as a placeholder to ensure the alignment would work out. Once the assets are available, it will be quick to replace those images.

Screenshot from 2019-03-30 15-03-15

**Comment by alexellis** [comment]
Lovely :+1: 

Can you check with the designer what should happen when on a smaller viewport like mobile?

**Comment by burtonr** [comment]
Still waiting for the resources and input from design, but I've gone and added the appropriate media queries to display properly on the various device screen sizes. Below is a gif showing the resize in action:

OpenFaaS-CTA-resizing

I also have screenshots of some various devices (phone, horizontal phone, tablet, desktop), but the images are quite large for a single comment. Available upon request!

**Comment by alexellis** [comment]
Derek close

**Pull request closed without merging**
